adjust error message from pylint

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -53,7 +53,23 @@ jobs:
             mkdir test-reports
             nosetests --with-coverage --with-xunit --cover-package=models --cover-package=controllers --cover-package=lambda_function.py --cover-erase --cover-branches
             mv .coverage test-reports/.coverage
-            pylint --exit-zero -f parseable controllers models lambda_function.py > test-reports/pylint.out
+            pylint -f parseable controllers models lambda_function.py > test-reports/pylint.out
+            # PyLint returns
+            # 0 if everything went fine
+            # 1 if some fatal message issued
+            # 2 if some error message issued
+            # 4 if some warning message issued
+            # 8 if some refactor message issued
+            # 16 if some convention message issued
+            # 32 on usage error
+            #status 1 to 16 will be bit-ORed so you can know which different
+            #categories has been issued by analysing pylint output status code
+            if [$? & (32+2+1)]; then
+               echo "error in pylint!" # pay attention to these errors!
+            else
+               echo "warning in pylint!" # ignore these errors
+               $? = 0
+            fi
 
       - store_artifacts:
           path: test-reports/
